#!/bin/bash
#
# Points the Reviewdeck cask in the Homebrew tap at a published release. The
# release workflow runs this once the GitHub release exists. The cask is
# rendered from scratch every time, so the first run creates Casks/reviewdeck.rb
# and every later run rewrites it - there is no bespoke first release.
#
#   VERSION=1.2.3 SHA256=<checksum of the zip> ./scripts/bump-cask.sh
#
# Environment:
#   VERSION     released version, with or without the leading v (required)
#   SHA256      sha256 of Reviewdeck-$VERSION-arm64.zip (required)
#   TAP_DIR     existing checkout of the tap - cloned over ssh when unset
#   TAP_REPO    owner/name of the tap (default: vojtechmares/homebrew-tap)
#   TAP_BRANCH  branch to commit on (default: master)
#   REPO        owner/name of this project (default: vojtechmares/reviewdeck)
#   DRY_RUN     1 to render and show the diff without committing or pushing
#
set -euo pipefail

REPO="${REPO:-vojtechmares/reviewdeck}"
TAP_REPO="${TAP_REPO:-vojtechmares/homebrew-tap}"
TAP_BRANCH="${TAP_BRANCH:-master}"
TAP_DIR="${TAP_DIR:-}"
DRY_RUN="${DRY_RUN:-0}"
VERSION="${VERSION:-}"
SHA256="${SHA256:-}"

die() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

VERSION="${VERSION#v}"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] ||
	die "VERSION must be a semver version, got '${VERSION:-<empty>}'"
[[ "$SHA256" =~ ^[0-9a-f]{64}$ ]] ||
	die "SHA256 must be a 64 character hex digest, got '${SHA256:-<empty>}'"

ZIP="Reviewdeck-$VERSION-arm64.zip"
URL="https://github.com/$REPO/releases/download/v$VERSION/$ZIP"

# A cask pointing at a 404 is worse than no cask, so make sure the asset is
# really there before writing anything.
echo "==> Checking $URL"
curl -fsIL -o /dev/null "$URL" ||
	die "$ZIP cannot be downloaded - is the release published?"

if [[ -n "$TAP_DIR" ]]; then
	[[ -d "$TAP_DIR/.git" ]] || die "TAP_DIR is not a git checkout: $TAP_DIR"
else
	TAP_DIR="$(mktemp -d)"
	trap 'rm -rf "$TAP_DIR"' EXIT
	echo "==> Cloning $TAP_REPO"
	git clone --quiet --depth 1 --branch "$TAP_BRANCH" \
		"git@github.com:$TAP_REPO.git" "$TAP_DIR"
fi

CASK="$TAP_DIR/Casks/reviewdeck.rb"
mkdir -p "$(dirname "$CASK")"

# Unquoted heredoc: $VERSION and friends expand, Ruby's #{version} does not
# look like a shell expansion and passes through untouched.
echo "==> Rendering Casks/reviewdeck.rb"
cat >"$CASK" <<RUBY
# This file is generated by the reviewdeck release workflow. DO NOT EDIT.
cask "reviewdeck" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/$REPO/releases/download/v#{version}/Reviewdeck-#{version}-arm64.zip"
  name "Reviewdeck"
  desc "Collects the code reviews waiting on you across every Git host"
  homepage "https://github.com/$REPO"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Reviewdeck.app"

  # Homebrew 6 removed "brew install --cask --no-quarantine", so the cask has to
  # clear the flag itself. Reviewdeck is ad-hoc signed but not notarised, and
  # Gatekeeper will not launch a quarantined bundle it cannot verify. Failing
  # here would abort the install after the app is already in place, and a
  # Gatekeeper prompt is the better of those two outcomes.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-d", "-r", "com.apple.quarantine", "#{appdir}/Reviewdeck.app"],
                   must_succeed: false
  end

  uninstall quit: "cz.mares.reviewdeck"

  # Electron names the data directory after package.json's "name" when running
  # from source and after the bundle when packaged, so both spellings are here.
  zap trash: [
    "~/Library/Application Support/Reviewdeck",
    "~/Library/Application Support/reviewdeck",
    "~/Library/Caches/cz.mares.reviewdeck",
    "~/Library/Preferences/cz.mares.reviewdeck.plist",
    "~/Library/Saved Application State/cz.mares.reviewdeck.savedState",
  ]

  caveats <<~EOS
    Reviewdeck is ad-hoc signed but not notarised. This cask clears the
    com.apple.quarantine flag on Reviewdeck.app after installing it, which is
    what lets it launch without Gatekeeper refusing to verify it.

    Access tokens are kept in the macOS Keychain via Electron's safeStorage;
    "brew uninstall --zap" removes the on-disk config but not the Keychain
    entry.
  EOS
end
RUBY

cd "$TAP_DIR"
git add Casks/reviewdeck.rb

if git diff --cached --quiet; then
	echo "==> Casks/reviewdeck.rb already points at $VERSION, nothing to do"
	exit 0
fi

git --no-pager diff --cached

if [[ "$DRY_RUN" == "1" ]]; then
	echo "==> Dry run, stopping here"
	exit 0
fi

# CI runners have no git identity; locally the global one is already set.
if ! git config user.email >/dev/null 2>&1; then
	git config user.name "github-actions[bot]"
	git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
fi

echo "==> Committing"
git commit --quiet --signoff -m "chore(reviewdeck): bump cask to $VERSION"

echo "==> Pushing to $TAP_BRANCH"
git push --quiet origin "HEAD:refs/heads/$TAP_BRANCH"

echo "==> $TAP_REPO now serves Reviewdeck $VERSION"
